<?php
namespace app\modules\user\forms;

use app\modules\core\interfaces\SaveModelInterface;
use app\modules\user\helpers\EmailConfirmStatusHelper;
use app\modules\user\helpers\UserStatusHelper;
use app\modules\user\models\User;
use yii\base\Model;
use yii\helpers\HtmlPurifier;

/**
 * Class UserFormModel
 * @package app\modules\user\forms
 */
class UserFormModel extends Model implements SaveModelInterface
{
    public $id;

    public $username;

    public $email;

    public $email_confirm;

    public $full_name;

    public $access_level;

    public $status;

    public $about;

    public $phone;


    /**
     * @return array
     */
    public function rules() {

        return [
            [
                [
                    'username',
                    'email',
                    'email_confirm',
                    'full_name',
                    'access_level',
                    'status',
                    'about',
                    'phone'
                ],
                'required'
            ],
            [
                [
                    'username',
                    'email',
                    'full_name',
                    'about',
                    'phone'
                ], 'filter', 'filter' => 'trim',],
            [
                ['username', 'email', 'full_name', 'about', 'phone' ], 'filter',
                'filter' => function ($html) {
                    return HtmlPurifier::process(
                        $html,
                        ['Attr.AllowedFrameTargets' => ['_blank'],]
                    );
                }
            ],
            ['username', 'unique', 'targetClass' => User::className(), 'message' => 'Имя пользователя уже занято', 'skipOnEmpty'=>$this->id === null],
            [
                'username',
                'match',
                'pattern' => '/^[A-Za-z0-9_-]{2,50}$/',
                'message' => 'Неверный формат поля "{attribute}" допустимы только буквы и цифры, от 2 до 20 символов'
            ],
            ['email', 'email'],
            ['status', 'in', 'range'=>array_keys(UserStatusHelper::getList())],
            ['email_confirm', 'in', 'range'=>array_keys(EmailConfirmStatusHelper::getList())],
            ['id', 'safe'],
        ];
    }


    /**
     * @param Model $model
     * @return bool|void
     */
    public function processingData(Model $model) {


    }


    /**
     * @return array
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'username' => 'Логин',
            'email' => 'Email',
            'email_confirm' => 'Подтверждение email',
            'hash' => 'Hash',
            'auth_key' => 'Auth Key',
            'user_ip' => 'IP пользователя',
            'status' => 'Статус',
            'status_change_at' => 'Время изменения статуса',
            'visited_at' => 'Последний визит',
            'registered_from' => 'Тип регистрации',
            'access_level' => 'Группа',
            'logged_in_from' => 'Logged In From',
            'logged_at' => 'Logged At',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'full_name' => 'ФИО',
            'avatar' => 'Аватар',
            'about' => 'Должность, место работы',
            'phone' => 'Телефон',
        ]; // TODO: Change the autogenerated stub
    }
}